name: Build and Push Docker Image

on:
  push:
    branches:
      - production
  pull_request:
    branches:
      - production
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      # - uses: vitr/actions-build-and-upload-to-ecs@master
      #   with:
      #     access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      #     secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      #     account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      #     repo: astrite-app-api
      #     region: ap-southeast-1
      #     tags: latest,${{ github.sha }}
      #     create_repo: true

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build . -t ghcr.io/${{ github.repository_owner }}/astrite-app-api:latest

      - name: Push Docker image
        run: docker push ghcr.io/${{ github.repository_owner }}/astrite-app-api:latest
