name: Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: oven-sh/setup-bun@v2

      - uses: actions/cache@v4
        name: Setup cache
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-pnpm-cache-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: pnpm run typecheck
        run: pnpm run typecheck

      - name: pnpm run lint
        run: pnpm run lint
